version: '2'
services:
    zoo1:
        image: zookeeper
        container_name: zoo1
        ports:
            - "2181:2181"
        environment: #环境变量
            #ZOO_MY_ID是ZK服务的id, 它是1-255之间的整数, 必须在集群中唯一
            ZOO_MY_ID: 1
            #ZOO_SERVERS是ZK集群的主机列表
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper
        container_name: zoo2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper
        container_name: zoo3
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888